interface Rate {
  standardCodeId: string;
}

export const rates: Rate[] = [
  { standardCodeId: 'EXERCITATIONEM' },
  { standardCodeId: 'VITAE' },
  { standardCodeId: 'UT' },
  { standardCodeId: 'FUGA' },
  { standardCodeId: 'DOLORES' },
  { standardCodeId: 'CUPIDITATE' },
  { standardCodeId: 'SED' },
  { standardCodeId: 'OMNIS' },
  { standardCodeId: 'EUM' },
  { standardCodeId: 'ASPERNATUR' },
  { standardCodeId: 'VOLUPTATEM' },
  { standardCodeId: 'EXPLICABO' },
  { standardCodeId: 'DOLORIBUS' },
  { standardCodeId: 'OPTIO' },
  { standardCodeId: 'UT' },
  { standardCodeId: 'PRAESENTIUM' },
  { standardCodeId: 'SINT' },
  { standardCodeId: 'DOLORES' },
  { standardCodeId: 'ADIPISCI' },
  { standardCodeId: 'VEL' },
  { standardCodeId: 'SOLUTA' },
  { standardCodeId: 'OFFICIIS' },
  { standardCodeId: 'ET' },
  { standardCodeId: 'QUOS' },
  { standardCodeId: 'MOLLITIA' },
  { standardCodeId: 'VOLUPTATES' },
  { standardCodeId: 'RERUM' },
  { standardCodeId: 'DOLOR' },
  { standardCodeId: 'ENIM' },
  { standardCodeId: 'VOLUPTATEM' },
  { standardCodeId: 'EXERCITATIONEM' },
  { standardCodeId: 'ET' },
  { standardCodeId: 'NECESSITATIBUS' },
  { standardCodeId: 'ARCHITECTO' },
  { standardCodeId: 'TENETUR' },
  { standardCodeId: 'UNDE' },
  { standardCodeId: 'TEMPORE' },
  { standardCodeId: 'ALIQUID' },
  { standardCodeId: 'OCCAECATI' },
  { standardCodeId: 'ENIM' },
  { standardCodeId: 'AUT' },
  { standardCodeId: 'UT' },
  { standardCodeId: 'DISTINCTIO' },
  { standardCodeId: 'RERUM' },
  { standardCodeId: 'CUMQUE' },
  { standardCodeId: 'ET' },
  { standardCodeId: 'TEMPORA' },
  { standardCodeId: 'REM' },
  { standardCodeId: 'HARUM' },
  { standardCodeId: 'VITAE' },
  { standardCodeId: 'DOLOREMQUE' },
  { standardCodeId: 'ET' },
  { standardCodeId: 'QUIA' },
  { standardCodeId: 'OMNIS' },
  { standardCodeId: 'QUI' },
  { standardCodeId: 'ID' },
  { standardCodeId: 'NIHIL' },
  { standardCodeId: 'REPELLENDUS' },
  { standardCodeId: 'PERFERENDIS' },
  { standardCodeId: 'VOLUPTATUM' },
  { standardCodeId: 'QUAE' },
  { standardCodeId: 'NEQUE' },
  { standardCodeId: 'SINT' },
  { standardCodeId: 'OPTIO' },
  { standardCodeId: 'LIBERO' },
  { standardCodeId: 'REPREHENDERIT' },
  { standardCodeId: 'PARIATUR' },
  { standardCodeId: 'DISTINCTIO' },
  { standardCodeId: 'VERITATIS' },
  { standardCodeId: 'DOLOREMQUE' },
  { standardCodeId: 'VOLUPTAS' },
  { standardCodeId: 'SUNT' },
  { standardCodeId: 'SOLUTA' },
  { standardCodeId: 'ADIPISCI' },
  { standardCodeId: 'SIT' },
  { standardCodeId: 'NON' },
  { standardCodeId: 'PLACEAT' },
  { standardCodeId: 'ENIM' },
  { standardCodeId: 'QUI' },
  { standardCodeId: 'OMNIS' },
  { standardCodeId: 'IPSA' },
  { standardCodeId: 'QUIS' },
  { standardCodeId: 'PERFERENDIS' },
  { standardCodeId: 'VOLUPTATUM' },
  { standardCodeId: 'QUAE' },
  { standardCodeId: 'NEQUE' },
  { standardCodeId: 'SINT' },
  { standardCodeId: 'DIGNISSIMOS' },
  { standardCodeId: 'ODIT' },
  { standardCodeId: 'REPUDIANDAE' },
  { standardCodeId: 'AUTEM' },
  { standardCodeId: 'TEMPORE' },
  { standardCodeId: 'ALIQUAM' },
  { standardCodeId: 'VEL' },
  { standardCodeId: 'VERO' },
  { standardCodeId: 'A' },
  { standardCodeId: 'REPREHENDERIT' },
  { standardCodeId: 'PARIATUR' },
  { standardCodeId: 'DISTINCTIO' },
  { standardCodeId: 'VERITATIS' },
  { standardCodeId: 'DOLOREMQUE' },
  { standardCodeId: 'VOLUPTAS' },
];

export const standardCodes = [
  { _id: 'EXERCITATIONEM', name: 'aliquam reiciendis voluptatem' },
  { _id: 'VITAE', name: 'inventore alias a' },
  { _id: 'UT', name: 'nobis voluptatem quisquam' },
  { _id: 'FUGA', name: 'laudantium quia explicabo' },
  { _id: 'DOLORES', name: 'corrupti necessitatibus eveniet' },
  { _id: 'CUPIDITATE', name: 'nihil assumenda temporibus' },
  { _id: 'SED', name: 'illum et voluptatum' },
  { _id: 'OMNIS', name: 'consequatur sequi aut' },
  { _id: 'EUM', name: 'adipisci itaque in' },
  { _id: 'ASPERNATUR', name: 'atque minima blanditiis' },
  { _id: 'VOLUPTATEM', name: 'ducimus praesentium perspiciatis' },
  { _id: 'EXPLICABO', name: 'inventore harum blanditiis' },
  { _id: 'DOLORIBUS', name: 'in distinctio delectus' },
  { _id: 'OPTIO', name: 'animi molestias quas' },
  { _id: 'UT', name: 'ratione corporis voluptatem' },
  { _id: 'PRAESENTIUM', name: 'temporibus libero voluptate' },
  { _id: 'SINT', name: 'enim reiciendis officiis' },
  { _id: 'DOLORES', name: 'ipsam repudiandae beatae' },
  { _id: 'ADIPISCI', name: 'repellat aliquam aut' },
  { _id: 'VEL', name: 'velit ab eligendi' },
  { _id: 'SOLUTA', name: 'maxime eos et' },
  { _id: 'OFFICIIS', name: 'laborum necessitatibus nulla' },
  { _id: 'ET', name: 'quaerat amet officiis' },
  { _id: 'QUOS', name: 'et ut consequatur' },
  { _id: 'MOLLITIA', name: 'molestiae nostrum eaque' },
  { _id: 'VOLUPTATES', name: 'quod unde laudantium' },
  { _id: 'RERUM', name: 'dolorum est iure' },
  { _id: 'DOLOR', name: 'dolor qui praesentium' },
  { _id: 'ENIM', name: 'aliquid neque reiciendis' },
  { _id: 'VOLUPTATEM', name: 'earum sit veniam' },
  { _id: 'EXERCITATIONEM', name: 'ex magnam expedita' },
  { _id: 'ET', name: 'at ab ipsam' },
  { _id: 'NECESSITATIBUS', name: 'consequatur et placeat' },
  { _id: 'ARCHITECTO', name: 'doloribus eum distinctio' },
  { _id: 'TENETUR', name: 'enim doloribus commodi' },
  { _id: 'UNDE', name: 'quasi qui et' },
  { _id: 'TEMPORE', name: 'autem dolore alias' },
  { _id: 'ALIQUID', name: 'est quis laborum' },
  { _id: 'OCCAECATI', name: 'eligendi ullam qui' },
  { _id: 'ENIM', name: 'itaque veritatis ut' },
  { _id: 'AUT', name: 'expedita alias quo' },
  { _id: 'UT', name: 'eos nostrum vel' },
  { _id: 'DISTINCTIO', name: 'quibusdam et nulla' },
  { _id: 'RERUM', name: 'praesentium autem ab' },
  { _id: 'CUMQUE', name: 'est voluptatum incidunt' },
  { _id: 'ET', name: 'deserunt dignissimos qui' },
  { _id: 'TEMPORA', name: 'ducimus fugiat nobis' },
  { _id: 'REM', name: 'iste quod ab' },
  { _id: 'HARUM', name: 'nihil quidem exercitationem' },
  { _id: 'VITAE', name: 'atque rerum sint' },
  { _id: 'DOLOREMQUE', name: 'necessitatibus in voluptates' },
  { _id: 'ET', name: 'corrupti ipsa repudiandae' },
  { _id: 'QUIA', name: 'dolorem vero enim' },
  { _id: 'OMNIS', name: 'animi neque quo' },
  { _id: 'QUI', name: 'esse aut sunt' },
  { _id: 'ID', name: 'sequi fuga reprehenderit' },
  { _id: 'NIHIL', name: 'placeat qui expedita' },
  { _id: 'REPELLENDUS', name: 'adipisci possimus velit' },
  { _id: 'PERFERENDIS', name: 'nihil rerum non' },
  { _id: 'VOLUPTATUM', name: 'doloremque possimus cupiditate' },
  { _id: 'QUAE', name: 'neque est doloribus' },
  { _id: 'NEQUE', name: 'quae veritatis non' },
  { _id: 'SINT', name: 'magnam repellendus sunt' },
  { _id: 'OPTIO', name: 'ad vero omnis' },
  { _id: 'LIBERO', name: 'non eos doloremque' },
  { _id: 'QUIA', name: 'tempore ducimus enim' },
  { _id: 'EA', name: 'impedit voluptas et' },
  { _id: 'MAGNI', name: 'porro voluptas quod' },
  { _id: 'SIT', name: 'inventore atque quis' },
  { _id: 'VOLUPTATEM', name: 'provident exercitationem nesciunt' },
  { _id: 'CONSECTETUR', name: 'repellat pariatur animi' },
  { _id: 'DELECTUS', name: 'nobis dicta fugiat' },
  { _id: 'SUNT', name: 'distinctio rerum voluptatibus' },
  { _id: 'SOLUTA', name: 'quo expedita minus' },
  { _id: 'ADIPISCI', name: 'minima aut est' },
  { _id: 'SIT', name: 'sit dicta impedit' },
  { _id: 'NON', name: 'neque molestias vero' },
  { _id: 'PLACEAT', name: 'explicabo est delectus' },
  { _id: 'ENIM', name: 'voluptas at sequi' },
  { _id: 'QUI', name: 'consequatur magni aspernatur' },
  { _id: 'OMNIS', name: 'sed aut amet' },
  { _id: 'IPSA', name: 'eos dolorum doloremque' },
  { _id: 'QUIS', name: 'aut aliquam unde' },
  { _id: 'DIGNISSIMOS', name: 'fugiat ex quam' },
  { _id: 'ODIT', name: 'id corporis voluptate' },
  { _id: 'REPUDIANDAE', name: 'officiis dolores voluptas' },
  { _id: 'AUTEM', name: 'laboriosam ea quaerat' },
  { _id: 'TEMPORE', name: 'quos et expedita' },
  { _id: 'ALIQUAM', name: 'dolorem ut et' },
  { _id: 'VEL', name: 'et ullam quod' },
  { _id: 'VERO', name: 'iste repellendus distinctio' },
  { _id: 'A', name: 'asperiores animi dolores' },
  { _id: 'REPREHENDERIT', name: 'qui et quia' },
  { _id: 'PARIATUR', name: 'hic sit vel' },
  { _id: 'DISTINCTIO', name: 'consequuntur dolores modi' },
  { _id: 'VERITATIS', name: 'est aliquid consequatur' },
  { _id: 'ET', name: 'voluptates inventore porro' },
  { _id: 'ASPERNATUR', name: 'cum culpa qui' },
  { _id: 'DOLOREMQUE', name: 'porro qui aperiam' },
  { _id: 'VOLUPTAS', name: 'vel aliquid alias' },
];
